#!/usr/bin/env bash
# bash script to configure nginx web server 
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo -e "Ceci n'est pas une page" | sudo tee /var/www/error/custom_404.html

default=\
"
	server {
		listen 80 default_server;
		       	  listen [::]:80 default_server;
			  	 	 root /var/www/html;
						index index.html index.htm index.nginx-debian.html;
						      		 server_name _;
										error_page 404 /custom_404.html;
											       location /custom_404.html {
																	root /var/www/error;
																				internal;
																						}
																								location / {
																											try_files \$uri \$uri/ =404;
																												  	}
																															location /redirect_me/ {
																																			rewrite ^(.*)$ http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;	
																																				       }
}"
echo "$default" > /etc/nginx/sites-available/default
sudo service nginx restart
