#!/usr/bin/env bash
# The bash script to display the below content of the file
#     User name
#     User ID
#     Home directory path for user

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
    echo $f1:$f3:$f6
done < /etc/passwd
