#!/usr/bin/env bash
# The bash script to display the below content of the file
#     User name
#     User ID
#     Home directory path for user

# shellcheck disable=SC2043
while IFS=: read -r f
do
    echo "$f" | cut -f 1,2,6 -d ':'
done < /etc/passwd
