#!/usr/bin/env bash
# Bash script that displays:
#         The content of the current directory
#         In a list format
#         Where only the part of the name after the first dash is displayed

#file_ls="$(pwd $(ls))"
for files in *
do
    echo "$files" | cut -d '-' -f 2-
done

